name: Java CI with Maven   # Bu pipeline’ın ismi

on:
  push:                   # Kod GitHub'a gönderildiğinde
    branches: [ "main" ]  # main branch için çalışsın
  pull_request:           # Biri PR açarsa da çalışsın
    branches: [ "main" ]

jobs:                     # Yapılacak işler listesi
  build:
    runs-on: ubuntu-latest   # Linux sunucusunda çalışacak

    steps:
      - name: Checkout code    # 1. Kodu GitHub’tan indir
        uses: actions/checkout@v3

      - name: Set up JDK 21    # 2. Java ortamını hazırla
        uses: actions/setup-java@v3
        with:
          java-version: '17cleart'
          distribution: 'temurin'

      - name: Build with Maven # 3. Maven ile build et
        run: mvn clean install -DskipTests

      - name: Run tests        # 4. Testleri çalıştır
        run: mvn test